# Generated by Django 3.1.4 on 2020-12-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
